name: automerge

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.FLAKE_LOCK_PAT }}
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_FORKS: "false"
          UPDATE_LABELS: ""
          MERGE_LABELS: ""
